sonar.projectKey=Insaner1980_row-tool
sonar.organization=insaner1980
sonar.host.url=https://sonarcloud.io
sonar.projectVersion=1.0.0

sonar.exclusions=**/build/**,**/generated/**
sonar.cpd.exclusions=**/build/**,**/generated/**
sonar.secrets.excluded.file.suffixes=.webp
sonar.scm.use.blame.algorithm=GIT_NATIVE_BLAME
