package com.finnvek.rowtool.ui.theme

import androidx.compose.ui.graphics.Color

internal val DarkBackground = Color(0xFF1E1E12)
internal val DarkAlternateBackground = Color(0xFF252518)
internal val DarkSurface = Color(0xFF2E2E20)
internal val DarkSurfaceRaised = Color(0xFF3A3A2A)
internal val DarkSurfaceHighest = Color(0xFF454535)
internal val DarkPrimary = Color(0xFFC45100)
internal val DarkPrimaryContainer = Color(0xFFD4722A)
internal val DarkSecondary = Color(0xFF93AE4F)
internal val DarkSecondaryMuted = Color(0xFF6B8A35)
internal val DarkSecondaryContainer = Color(0xFF3A4020)
internal val DarkTertiary = Color(0xFFC9A435)
internal val DarkTertiaryContainer = Color(0xFF3A3520)
internal val DarkText = Color(0xFFE8E4D0)
internal val DarkTextSecondary = Color(0xFFB8B4A0)
internal val DarkTextMuted = Color(0xFFA8A491)
internal val DarkDisabled = Color(0xFF5A5840)
internal val DarkError = Color(0xFFC44D4D)
internal val DarkErrorContainer = Color(0xFF3A2020)
internal val DarkSuccess = Color(0xFF8BA44A)
internal val DarkNavigation = Color(0xFF161610)

internal val LightBackground = Color(0xFFE8E4D0)
internal val LightAlternateBackground = Color(0xFFDDD8C3)
internal val LightSurface = Color(0xFFD2CDB5)
internal val LightSurfaceRaised = Color(0xFFBBB59A)
internal val LightSurfaceMediumHigh = Color(0xFFC8C3A8)
internal val LightSurfaceHighest = Color(0xFFA49D80)
internal val LightPrimary = Color(0xFFC45100)
internal val LightSecondary = Color(0xFF394B18)
internal val LightSecondaryMuted = Color(0xFF5A7525)
internal val LightSecondaryContainer = Color(0xFFD0DDB5)
internal val LightTertiary = Color(0xFF9A7B18)
internal val LightTertiaryContainer = Color(0xFFE8DFB5)
internal val LightText = Color(0xFF2E2A1E)
internal val LightTextSecondary = Color(0xFF4C4634)
internal val LightTextMuted = Color(0xFF4A473C)
internal val LightDisabled = Color(0xFFC0BAA5)
internal val LightError = Color(0xFF8B3030)
internal val LightErrorContainer = Color(0xFFEAD0D0)
internal val LightDivider = Color(0xFFC5C0A8)
